### ISSUE TITLE
Singleton creation is not quite right

### ISSUE THREAD

**Issue by anandsaw** [WeroNikaNa/tetrisAthens#52]
When you create a singleton, the object should only be created dynamically when the getInstance method is invoked. Right now you create an instance no matter what irrespective of its need. Apart from that the instance creation should be thread safe. Please refer to slides from the lecture to see how a Singleton class is usually written.

**Comment by Kajkacz** [comment]
Anandsaw, I think it's the solution that was presented by the professor during the lecture, it was on slides described as Solution 2, is there a difference between that and our implementation?
